# -*- coding: utf-8 -*-
"""scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L01sEHS0Dca6tGbRURJsX0juZXGr77Wh
"""

import requests
from bs4 import BeautifulSoup
import json

# ターゲットにする映画館のURL（例として映画.comのイオンシネマ常滑のページ）
TARGET_URL = "https://eiga.com/theater/23/232001/4170/"

def fetch_movies():
    print(f"{TARGET_URL} からデータを取得します...")
    # サイトによってはプログラムからのアクセスを弾くため、ブラウザからのアクセスのように装う
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
    response = requests.get(TARGET_URL, headers=headers)

    movie_list = []

    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')

        # 映画.comの構造に合わせて、作品名が入っているタグを抽出（※サイトの仕様変更で変わる場合があります）
        # <h2 itemprop="name">...</h2> のような部分を狙い撃ちします
        titles = soup.select('h2.title-xlarge a')

        for t in titles:
            title_text = t.text.strip()
            if title_text and title_text not in movie_list:
                movie_list.append(title_text)

        print(f"{len(movie_list)}件の映画が見つかりました。")
    else:
        print(f"通信エラー: {response.status_code}")

    # 取得したリストを movies.json として保存
    output_data = {
        "cinema_name": "イオンシネマ常滑",
        "movies": movie_list
    }

    with open("movies.json", "w", encoding="utf-8") as f:
        json.dump(output_data, f, ensure_ascii=False, indent=2)
    print("movies.json に保存しました。")

if __name__ == "__main__":
    fetch_movies()